#!/bin/bash

TMPDIR="/tmp/drupal-update"
SHPATH=`dirname $0`

if [ "$2" == "" ] ; then
  echo "drupal-update <config> <version>"
  exit 1
fi

CONFIG_STR=`grep -e "^$1:" ${SHPATH}/conf`
if [ "${CONFIG_STR}" == "" ] ; then
  echo "config not found"
  exit 1
fi

USER=`echo ${CONFIG_STR} | cut -d: -f2`
HOST=`echo ${CONFIG_STR} | cut -d: -f3`
DESTPATH=`echo ${CONFIG_STR} | cut -d: -f4`
if [ "$DESTPATH" == "" ] ; then
  DESTPATH="public_html/"
fi

VERSION=$2

mkdir "$TMPDIR"
cd "$TMPDIR"

FILE="drupal-${VERSION}.tar.gz"
URL="https://ftp.drupal.org/files/projects/$FILE"
wget -O - $URL | tar xvfz - --strip-components=1
if [ "$?" != "0" ] ; then
  echo "An error occured when downloading drupal archive!"
  exit 1
fi

echo "Installing new version on ${USER}@${HOST}"

lftp -e "set ssl:verify-certificate no ; mirror --parallel=10 -R . --exclude=.htaccess --exclude=robots.txt $DESTPATH;quit" -u "$USER" "$HOST"

cd
rm -rf "$TMPDIR"
