#!/bin/bash

TMPDIR="/tmp/drupal-update"
SHPATH=`dirname $0`

if [ "$1" == "" ] ; then
  echo "drupal-update <config>"
  exit 1
fi

CONFIG_STR=`grep -e "^$1:" ${SHPATH}/conf`
if [ "${CONFIG_STR}" == "" ] ; then
  echo "config not found"
  exit 1
fi

USER=`echo ${CONFIG_STR} | cut -d: -f2`
HOST=`echo ${CONFIG_STR} | cut -d: -f3`

mkdir "$TMPDIR"
cd "$TMPDIR"

VERSION=`wget -O- https://www.drupal.org/project/drupal | egrep '"/drupal-7\\..*-release-notes' | egrep -o '7\.[0-9]+' | cut -f1 -d" "`
if [ "$VERSION" == "" ] ; then
  echo "Could not parse drupal version!"
  exit 1
fi
echo "New drupal version: $VERSION"

URL="http://ftp.drupal.org/files/projects/drupal-$VERSION.tar.gz"
wget -O - $URL | tar xvfz - --strip-components=1
if [ "$?" != "0" ] ; then
  echo "An error occured when downloading drupal archive!"
  exit 1
fi

echo "Installing new version on ${USER}@${HOST}"

lftp -e "mirror -R . --exclude=.htaccess --exclude=robots.txt public_html/;quit" -u "$USER" "$HOST"

cd
rm -rf "$TMPDIR"
